// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2fEC1QcfEuRnHwHtW8DX6f7ABTlcGRy8',
    appId: '1:362158168248:web:3dd4522b9fc83d2a3afc4d',
    messagingSenderId: '362158168248',
    projectId: 'course-app-184ac',
    authDomain: 'course-app-184ac.firebaseapp.com',
    storageBucket: 'course-app-184ac.firebasestorage.app',
    measurementId: 'G-XNK0X3BPBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhyUOaKd45kGAfWEsOU3jftYNiEgiTNQ',
    appId: '1:362158168248:android:e5514df38c68ac013afc4d',
    messagingSenderId: '362158168248',
    projectId: 'course-app-184ac',
    storageBucket: 'course-app-184ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdTrKkpIIaAvQwWwrNm15oCVBid3Lgy5w',
    appId: '1:362158168248:ios:33f5c5d3b83394643afc4d',
    messagingSenderId: '362158168248',
    projectId: 'course-app-184ac',
    storageBucket: 'course-app-184ac.firebasestorage.app',
    iosBundleId: 'com.example.courseApp',
  );
}
